### ISSUE TITLE
Error getting world Data

### ISSUE THREAD

**Issue by Mirokira** [jcarbelbide/tog-crowdsourcing-server#3]
When opening the plugin something does not work.

**Comment by jcarbelbide** [comment]
Hey Mirokira, sorry for the late response here. I can't tell from your description what wasn't working at the time, but I'm going to assume that it's related to the web service being down. This is an ongoing issue we're running into due to the amount of users that the plugin has accumulated. The small server that hosts this plugin is not able to keep up unfortunately. I do have some optimizations planned to help, but life keeps getting in the way. Even then, the changes may only temporarily alleviate the issue. I'll close this issue since there is an open one on the main plugin repo:
https://github.com/jcarbelbide/tog-crowdsourcing/issues/12
